const URL='https://uinhyjqsqrgfczqrmcya.supabase.co';const KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';const H={'apikey':KEY,'Content-Type':'application/json','Prefer':'return=representation'};let categories=[],items=[],list=[],filter='All',query='';
const api=async(path,opt={})=>{const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:{...H,...opt.headers}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()};
const $=id=>document.getElementById(id);const itemCount=$('itemCount'),total=$('total'),shoppingGroups=$('shoppingGroups'),completedWrap=$('completedWrap'),completedCount=$('completedCount'),completedList=$('completedList'),clearPurchased=$('clearPurchased'),search=$('search'),chips=$('chips'),pantryList=$('pantryList'),shoppingView=$('shoppingView'),pantryView=$('pantryView'),title=$('title'),addBtn=$('addBtn'),modal=$('modal'),closeModal=$('closeModal'),saveCustom=$('saveCustom'),customName=$('customName'),customCategory=$('customCategory'),customQty=$('customQty'),customPrice=$('customPrice'),customNote=$('customNote'),missingItem=$('missingItem'),editModal=$('editModal'),closeEdit=$('closeEdit'),editItemName=$('editItemName'),editPrice=$('editPrice'),editNote=$('editNote'),saveEdit=$('saveEdit'),pantryEditModal=$('pantryEditModal'),closePantryEdit=$('closePantryEdit'),pantryEditName=$('pantryEditName'),pantryEditCategory=$('pantryEditCategory'),pantryEditPrice=$('pantryEditPrice'),pantryEditUnit=$('pantryEditUnit'),pantryEditNote=$('pantryEditNote'),savePantryEdit=$('savePantryEdit'),deletePantryItem=$('deletePantryItem');let editingId=null,editingPantryId=null;
const money=n=>n==null?'':('$'+Number(n).toFixed(2));const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){try{[categories,items,list]=await Promise.all([api('shop_categories?select=*&order=sort_order'),api('shop_items?select=*&active=eq.true&order=name'),api('shop_list?select=*&order=added_at')]);render()}catch(e){toast('Could not load data')}}
function enriched(l){const i=items.find(x=>x.id===l.item_id);return{...l,name:i?.name||l.custom_name||'Item',cat:i?.category_id||null,unit:i?.unit||null,price:l.price??i?.default_price??null}}
function render(){const opts=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');customCategory.innerHTML=opts;pantryEditCategory.innerHTML=opts;renderShopping();renderPantry()}
function renderShopping(){const active=list.filter(x=>!x.purchased).map(enriched),done=list.filter(x=>x.purchased).map(enriched);itemCount.textContent=active.length+' item'+(active.length===1?'':'s');total.textContent=money(active.reduce((s,x)=>s+(Number(x.price)||0)*Number(x.quantity),0));shoppingGroups.innerHTML='';
 const grouped=new Map();active.forEach(x=>{const k=x.cat||0;if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(x)});
 [...grouped.entries()].sort((a,b)=>(categories.find(x=>x.id===a[0])?.sort_order||99)-(categories.find(x=>x.id===b[0])?.sort_order||99)).forEach(([cid,arr])=>shoppingGroups.insertAdjacentHTML('beforeend',groupHTML(categories.find(c=>c.id===cid)?.name||'Other',arr,false)));
 if(!active.length)shoppingGroups.innerHTML='<div class="empty">Your shopping list is clear.<br>Add items from Pantry.</div>';
 completedWrap.classList.toggle('hidden',!done.length);completedCount.textContent=done.length;completedList.innerHTML=done.length?'<div class="card purchased">'+done.map(x=>itemHTML(x,true)).join('')+'</div>':''}
function groupHTML(name,arr,done){return '<div class="group"><div class="group-title">'+esc(name)+'</div><div class="card">'+arr.map(x=>itemHTML(x,done)).join('')+'</div></div>'}
function itemHTML(x,done){const p=x.price!=null?money(x.price)+(x.unit?' / '+esc(x.unit):''):'';return '<div class="item"><button class="check '+(done?'on':'')+'" onclick="togglePurchased('+x.id+','+!done+')">'+(done?'✓':'')+'</button><div class="item-info clickable" onclick="openEdit('+x.id+')"><div class="item-name">'+esc(x.name)+'</div>'+(x.note?'<div class="item-note">'+esc(x.note)+'</div>':'')+'</div>'+(!done?'<div class="qty"><button onclick="qty('+x.id+',-1)">−</button><span>'+Number(x.quantity)+'</span><button onclick="qty('+x.id+',1)">+</button></div>':'')+'<div class="price clickable" onclick="openEdit('+x.id+')">'+p+'</div></div>'}
function renderPantry(){chips.innerHTML=['All',...categories.map(c=>c.name)].map(n=>'<button class="chip '+(filter===n?'active':'')+'" onclick="setFilter(\''+n.replaceAll("'","\\'")+'\')">'+esc(n)+'</button>').join('');
 const cat=categories.find(c=>c.name===filter);const q=query.toLowerCase();const searching=q.length>0;const shown=items.filter(i=>(searching||filter==='All'||i.category_id===cat?.id)&&i.name.toLowerCase().includes(q));const groups=searching||filter==='All'?categories:categories.filter(c=>c.id===cat?.id);pantryList.innerHTML='';
 groups.forEach(c=>{const a=shown.filter(i=>i.category_id===c.id);if(a.length)pantryList.insertAdjacentHTML('beforeend','<div class="group"><div class="group-title">'+esc(c.name)+'</div><div class="card">'+a.map(i=>{const on=list.some(l=>l.item_id===i.id&&!l.purchased);return '<div class="item"><div class="item-info clickable" onclick="openPantryEdit('+i.id+')"><div class="item-name">'+esc(i.name)+'</div><div class="item-meta">'+[money(i.default_price),i.unit].filter(Boolean).join(' · ')+'</div></div><button class="pantry-add '+(on?'added':'')+'" onclick="togglePantry('+i.id+')">'+(on?'✓ Added':'+ Add')+'</button></div>'}).join('')+'</div></div>')});if(!pantryList.innerHTML)pantryList.innerHTML='<div class="empty">No pantry items found.</div>';missingItem.classList.toggle('hidden',!searching)}
async function togglePantry(id){const existing=list.find(l=>l.item_id===id&&!l.purchased);try{if(existing){await api('shop_list?id=eq.'+existing.id,{method:'DELETE'});list=list.filter(x=>x.id!==existing.id)}else{const i=items.find(x=>x.id===id),r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:id,quantity:1,price:i.default_price})});list.push(r[0])}render();}catch(e){toast('Could not update item')}}
async function togglePurchased(id,val){try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({purchased:val,updated_at:new Date().toISOString()})});list=list.map(x=>x.id===id?r[0]:x);render()}catch(e){toast('Could not update item')}}
async function qty(id,d){const x=list.find(l=>l.id===id);if(!x)return;const n=Math.max(1,Number(x.quantity)+d);try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({quantity:n})});list=list.map(y=>y.id===id?r[0]:y);renderShopping()}catch(e){toast('Could not change quantity')}}
function openPantryEdit(id){const i=items.find(x=>x.id===id);if(!i)return;editingPantryId=id;pantryEditName.value=i.name;pantryEditCategory.value=i.category_id;pantryEditPrice.value=i.default_price??'';pantryEditUnit.value=i.unit??'';pantryEditNote.value=i.note??'';pantryEditModal.classList.remove('hidden')}closePantryEdit.onclick=()=>pantryEditModal.classList.add('hidden');pantryEditModal.onclick=e=>{if(e.target===pantryEditModal)pantryEditModal.classList.add('hidden')};savePantryEdit.onclick=async()=>{const i=items.find(x=>x.id===editingPantryId);if(!i)return;const name=pantryEditName.value.trim();if(!name)return;try{const r=await api('shop_items?id=eq.'+editingPantryId,{method:'PATCH',body:JSON.stringify({name,category_id:Number(pantryEditCategory.value),default_price:pantryEditPrice.value===''?null:Number(pantryEditPrice.value),unit:pantryEditUnit.value.trim()||null,updated_at:new Date().toISOString()})});items=items.map(x=>x.id===editingPantryId?r[0]:x);pantryEditModal.classList.add('hidden');render();toast('Pantry item updated')}catch(e){toast('Could not update pantry item')}};deletePantryItem.onclick=async()=>{if(!editingPantryId||!confirm('Delete this item from the pantry?'))return;try{await api('shop_items?id=eq.'+editingPantryId,{method:'DELETE'});items=items.filter(x=>x.id!==editingPantryId);list=list.filter(x=>x.item_id!==editingPantryId);pantryEditModal.classList.add('hidden');render();toast('Pantry item deleted')}catch(e){toast('Could not delete pantry item')}};function setFilter(n){filter=n;renderPantry()}search.addEventListener('input',e=>{query=e.target.value;renderPantry()});
document.querySelectorAll('nav button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.dataset.view==='pantry';shoppingView.classList.toggle('hidden',p);pantryView.classList.toggle('hidden',!p);title.textContent=p?'Pantry':'Shopping List';addBtn.classList.remove('hidden')});
clearPurchased.onclick=async()=>{try{await api('shop_list?purchased=eq.true',{method:'DELETE'});list=list.filter(x=>!x.purchased);render()}catch(e){toast('Could not clear purchased')}};
function openAdd(prefill=''){customName.value=prefill;customCategory.innerHTML=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');modal.classList.remove('hidden')}addBtn.onclick=()=>openAdd();missingItem.onclick=()=>openAdd(query);closeModal.onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
saveCustom.onclick=async()=>{const name=customName.value.trim(),category_id=Number(customCategory.value);if(!name||!category_id)return;try{let pantry=items.find(i=>i.name.toLowerCase()===name.toLowerCase()&&i.category_id===category_id);if(!pantry){const ir=await api('shop_items',{method:'POST',body:JSON.stringify({name,category_id,default_price:customPrice.value===''?null:Number(customPrice.value)})});pantry=ir[0];items.push(pantry)}const existing=list.find(l=>l.item_id===pantry.id&&!l.purchased);if(!existing){const r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:pantry.id,quantity:Number(customQty.value)||1,price:customPrice.value===''?pantry.default_price:Number(customPrice.value),note:customNote.value.trim()||null})});list.push(r[0])}customName.value='';customQty.value=1;customPrice.value='';customNote.value='';modal.classList.add('hidden');render();toast('Saved to pantry and shopping list')}catch(e){toast('Could not add item')}};
function openEdit(id){const x=enriched(list.find(l=>l.id===id));if(!x)return;editingId=id;editItemName.textContent=x.name;editPrice.value=x.price??'';editNote.value=x.note??'';editModal.classList.remove('hidden')}
closeEdit.onclick=()=>editModal.classList.add('hidden');editModal.onclick=e=>{if(e.target===editModal)editModal.classList.add('hidden')};saveEdit.onclick=async()=>{if(!editingId)return;try{const r=await api('shop_list?id=eq.'+editingId,{method:'PATCH',body:JSON.stringify({price:editPrice.value===''?null:Number(editPrice.value),note:editNote.value.trim()||null,updated_at:new Date().toISOString()})});list=list.map(x=>x.id===editingId?r[0]:x);editModal.classList.add('hidden');renderShopping();toast('Item updated')}catch(e){toast('Could not update item')}};
function toast(s){toastEl=document.getElementById('toast');toastEl.textContent=s;toastEl.classList.remove('hidden');setTimeout(()=>toastEl.classList.add('hidden'),1800)}load();