const URL='https://uinhyjqsqrgfczqrmcya.supabase.co';const KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';const H={'apikey':KEY,'Content-Type':'application/json','Prefer':'return=representation'};let categories=[],items=[],list=[],recipes=[],recipeIngredients=[],filter='All',query='',recipeQuery='';const openRecipes=new Set();const CATEGORY_ORDER=['Produce','Bakery','Deli','Condiments','Meat','Dry Goods','Spices','Health & Beauty','Household','Drinks','Frozen','Dairy'];const sortCategories=()=>categories.sort((a,b)=>{const ai=CATEGORY_ORDER.indexOf(a.name),bi=CATEGORY_ORDER.indexOf(b.name);return (ai<0?999:ai)-(bi<0?999:bi)||a.name.localeCompare(b.name)});
const api=async(path,opt={})=>{const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:{...H,...opt.headers}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()};
const $=id=>document.getElementById(id);const recipesView=$('recipesView'),recipeList=$('recipeList'),recipeSearch=$('recipeSearch'),itemCount=$('itemCount'),total=$('total'),shoppingGroups=$('shoppingGroups'),completedWrap=$('completedWrap'),completedCount=$('completedCount'),completedList=$('completedList'),clearPurchased=$('clearPurchased'),search=$('search'),chips=$('chips'),pantryList=$('pantryList'),shoppingView=$('shoppingView'),pantryView=$('pantryView'),title=$('title'),addBtn=$('addBtn'),modal=$('modal'),closeModal=$('closeModal'),saveCustom=$('saveCustom'),customName=$('customName'),customCategory=$('customCategory'),customQty=$('customQty'),customPrice=$('customPrice'),customNote=$('customNote'),missingItem=$('missingItem'),editModal=$('editModal'),closeEdit=$('closeEdit'),editItemName=$('editItemName'),editPrice=$('editPrice'),editNote=$('editNote'),saveEdit=$('saveEdit'),pantryEditModal=$('pantryEditModal'),closePantryEdit=$('closePantryEdit'),pantryEditName=$('pantryEditName'),pantryEditCategory=$('pantryEditCategory'),pantryEditPrice=$('pantryEditPrice'),pantryEditUnit=$('pantryEditUnit'),pantryEditNote=$('pantryEditNote'),savePantryEdit=$('savePantryEdit'),deletePantryItem=$('deletePantryItem'),addRecipeBtn=$('addRecipeBtn'),recipeEditModal=$('recipeEditModal'),recipeEditTitle=$('recipeEditTitle'),closeRecipeEdit=$('closeRecipeEdit'),recipeEditName=$('recipeEditName'),recipeIngredientEditor=$('recipeIngredientEditor'),addIngredientRowBtn=$('addIngredientRow'),saveRecipe=$('saveRecipe'),deleteRecipe=$('deleteRecipe');let editingId=null,editingPantryId=null,editingRecipeId=null;
const money=n=>n==null?'':('$'+Number(n).toFixed(2));const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){try{[categories,items,list,recipes,recipeIngredients]=await Promise.all([api('shop_categories?select=*&order=sort_order'),api('shop_items?select=*&active=eq.true&order=name'),api('shop_list?select=*&order=added_at'),api('shop_recipes?select=*&order=sort_order'),api('shop_recipe_ingredients?select=*&order=sort_order')]);sortCategories();render()}catch(e){toast('Could not load data')}}
function enriched(l){const i=items.find(x=>x.id===l.item_id);return{...l,name:i?.name||l.custom_name||'Item',cat:i?.category_id||null,unit:i?.unit||null,price:l.price??i?.default_price??null}}
function render(){sortCategories();const opts=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');customCategory.innerHTML=opts;pantryEditCategory.innerHTML=opts;renderShopping();renderPantry();renderRecipes()}
function renderShopping(){const active=list.filter(x=>!x.purchased).map(enriched),done=list.filter(x=>x.purchased).map(enriched);itemCount.textContent=active.length+' item'+(active.length===1?'':'s');total.textContent=money(active.reduce((s,x)=>s+(Number(x.price)||0)*Number(x.quantity),0));shoppingGroups.innerHTML='';
 const grouped=new Map();active.forEach(x=>{const k=x.cat||0;if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(x)});
 [...grouped.entries()].sort((a,b)=>(categories.find(x=>x.id===a[0])?.sort_order||99)-(categories.find(x=>x.id===b[0])?.sort_order||99)).forEach(([cid,arr])=>shoppingGroups.insertAdjacentHTML('beforeend',groupHTML(categories.find(c=>c.id===cid)?.name||'Other',arr,false)));
 if(!active.length)shoppingGroups.innerHTML='<div class="empty">Your shopping list is clear.<br>Add items from Pantry.</div>';
 completedWrap.classList.toggle('hidden',!done.length);completedCount.textContent=done.length;completedList.innerHTML=done.length?'<div class="card purchased">'+done.map(x=>itemHTML(x,true)).join('')+'</div>':''}
function groupHTML(name,arr,done){return '<div class="group"><div class="group-title">'+esc(name)+'</div><div class="card">'+arr.map(x=>itemHTML(x,done)).join('')+'</div></div>'}
function itemHTML(x,done){const p=x.price!=null?money(x.price)+(x.unit?' / '+esc(x.unit):''):'';return '<div class="item"><button class="check '+(done?'on':'')+'" onclick="togglePurchased('+x.id+','+!done+')">'+(done?'✓':'')+'</button><div class="item-info clickable" onclick="openEdit('+x.id+')"><div class="item-name">'+esc(x.name)+'</div>'+(x.note?'<div class="item-note">'+esc(x.note)+'</div>':'')+'</div>'+(!done?'<div class="qty"><button onclick="qty('+x.id+',-1)">−</button><span>'+Number(x.quantity)+'</span><button onclick="qty('+x.id+',1)">+</button></div>':'')+'<div class="price clickable" onclick="openEdit('+x.id+')">'+p+'</div></div>'}
function renderPantry(){chips.innerHTML=['All',...categories.map(c=>c.name)].map(n=>'<button class="chip '+(filter===n?'active':'')+'" onclick="setFilter(\''+n.replaceAll("'","\\'")+'\')">'+esc(n)+'</button>').join('');
 const cat=categories.find(c=>c.name===filter);const q=query.toLowerCase();const searching=q.length>0;const shown=items.filter(i=>(searching||filter==='All'||i.category_id===cat?.id)&&i.name.toLowerCase().includes(q));const groups=searching||filter==='All'?categories:categories.filter(c=>c.id===cat?.id);pantryList.innerHTML='';
 groups.forEach(c=>{const a=shown.filter(i=>i.category_id===c.id);if(a.length)pantryList.insertAdjacentHTML('beforeend','<div class="group"><div class="group-title">'+esc(c.name)+'</div><div class="card">'+a.map(i=>{const on=list.some(l=>l.item_id===i.id&&!l.purchased);return '<div class="swipe-row" data-pantry-id="'+i.id+'"><div class="swipe-actions"><button class="swipe-edit" onclick="openPantryEdit('+i.id+')">Edit</button><button class="swipe-delete" onclick="quickDeletePantry('+i.id+')">Delete</button></div><div class="item swipe-item"><div class="item-info"><div class="item-name">'+esc(i.name)+'</div><div class="item-meta">'+[money(i.default_price),i.unit].filter(Boolean).join(' · ')+'</div></div><button class="pantry-add '+(on?'added':'')+'" onclick="togglePantry('+i.id+')">'+(on?'✓ Added':'+ Add')+'</button></div></div>'}).join('')+'</div></div>')});if(!pantryList.innerHTML)pantryList.innerHTML='<div class="empty">No pantry items found.</div>';missingItem.classList.toggle('hidden',!searching);initPantrySwipes()}
function recipeIngredientHTML(x){const pantry=items.find(i=>i.name.trim().toLowerCase()===x.ingredient_name.trim().toLowerCase());const on=pantry&&list.some(l=>l.item_id===pantry.id&&!l.purchased);return '<div class="recipe-ing"><button class="recipe-check '+(on?'on':'')+'" onclick="addRecipeIngredient('+x.id+')">'+(on?'✓':'')+'</button><span>'+esc(x.ingredient_name)+'</span><button class="recipe-add '+(on?'added':'')+'" onclick="addRecipeIngredient('+x.id+')">'+(on?'Added':'+ Add')+'</button></div>'}
function renderRecipes(){const q=recipeQuery.toLowerCase();const shown=recipes.filter(r=>r.name.toLowerCase().includes(q));recipeList.innerHTML=shown.map(r=>{const ing=recipeIngredients.filter(x=>x.recipe_id===r.id);return '<div class="recipe-card swipe-row recipe-swipe-row"><div class="swipe-actions"><button class="swipe-edit" onclick="openRecipeEditor('+r.id+')">Edit</button><button class="swipe-delete" onclick="quickDeleteRecipe('+r.id+')">Delete</button></div><div class="recipe-swipe-item swipe-item"><button class="recipe-head" onclick="toggleRecipe('+r.id+')"><span>'+esc(r.name)+'</span><span class="recipe-count">'+ing.length+' ingredients</span><span class="recipe-chevron">⌄</span></button><div class="recipe-body '+(openRecipes.has(r.id)?'':'hidden')+'" id="recipe-'+r.id+'">'+ing.map(recipeIngredientHTML).join('')+'</div></div></div>'}).join('')||'<div class="empty">No recipes found.</div>';initSwipeRows()}
function toggleRecipe(id){const el=$('recipe-'+id);if(!el)return;if(openRecipes.has(id)){openRecipes.delete(id);el.classList.add('hidden')}else{openRecipes.add(id);el.classList.remove('hidden')}}
async function addRecipeIngredient(id){const ri=recipeIngredients.find(x=>x.id===id);if(!ri)return;openRecipes.add(ri.recipe_id);let pantry=items.find(i=>i.name.trim().toLowerCase()===ri.ingredient_name.trim().toLowerCase());try{if(pantry){const existing=list.find(l=>l.item_id===pantry.id&&!l.purchased);if(existing){await api('shop_list?id=eq.'+existing.id,{method:'DELETE'});list=list.filter(x=>x.id!==existing.id);renderShopping();renderPantry();renderRecipes();toast(ri.ingredient_name+' removed');return}}if(!pantry){const cat=categories.find(c=>c.name==='Dry Goods')||categories[0];const ir=await api('shop_items',{method:'POST',body:JSON.stringify({name:ri.ingredient_name.trim(),category_id:cat.id})});pantry=ir[0];items.push(pantry)}const r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:pantry.id,quantity:1,price:pantry.default_price})});list.push(r[0]);renderShopping();renderPantry();renderRecipes();toast(ri.ingredient_name+' added')}catch(e){toast('Could not update ingredient')}}
recipeSearch.addEventListener('input',e=>{recipeQuery=e.target.value;renderRecipes()});function ingredientEditorRow(name=''){return '<div class="ingredient-edit-row"><div class="recipe-ing-picker"><input class="recipe-ing-input" value="'+esc(name)+'" placeholder="Start typing a pantry item…" autocomplete="off" oninput="recipeIngredientSearch(this)" onfocus="recipeIngredientSearch(this)"><div class="recipe-ing-results hidden"></div></div><button type="button" onclick="this.parentElement.remove()">×</button></div>'}
function recipeIngredientSearch(input){const box=input.parentElement.querySelector('.recipe-ing-results'),q=input.value.trim().toLowerCase();document.querySelectorAll('.recipe-ing-results').forEach(x=>{if(x!==box)x.classList.add('hidden')});if(!q){box.classList.add('hidden');return}const matches=items.filter(i=>i.name.toLowerCase().includes(q)).slice(0,8);box.innerHTML=matches.map(i=>'<button type="button" onclick="chooseRecipePantryItem(this,'+i.id+')"><span>'+esc(i.name)+'</span><small>'+esc(categories.find(c=>c.id===i.category_id)?.name||'Pantry')+'</small></button>').join('')+'<button type="button" class="recipe-new-ing" onclick="addMissingRecipeIngredient(this)"><span>Item missing?</span><small>Add “'+esc(input.value.trim())+'” to Pantry</small></button>';box.classList.remove('hidden')}
function chooseRecipePantryItem(btn,id){const i=items.find(x=>x.id===id),wrap=btn.closest('.recipe-ing-picker');if(!i)return;wrap.querySelector('.recipe-ing-input').value=i.name;wrap.querySelector('.recipe-ing-results').classList.add('hidden')}
function addMissingRecipeIngredient(btn){const wrap=btn.closest('.recipe-ing-picker'),input=wrap.querySelector('.recipe-ing-input'),name=input.value.trim();if(!name)return;wrap.querySelector('.recipe-ing-results').classList.add('hidden');openAdd(name);customName.dataset.recipeTarget='1'}

function addRecipeIngredientRow(name=''){recipeIngredientEditor.insertAdjacentHTML('afterbegin',ingredientEditorRow(name));const first=recipeIngredientEditor.querySelector('.recipe-ing-input');if(first)first.focus()}
function openRecipeEditor(id=null){editingRecipeId=id;const r=recipes.find(x=>x.id===id);recipeEditTitle.textContent=id?'Edit recipe':'Add recipe';recipeEditName.value=r?.name||'';const ing=id?recipeIngredients.filter(x=>x.recipe_id===id).sort((a,b)=>a.sort_order-b.sort_order):[];recipeIngredientEditor.innerHTML=ing.map(x=>ingredientEditorRow(x.ingredient_name)).join('');if(!ing.length)addRecipeIngredientRow();deleteRecipe.classList.toggle('hidden',!id);recipeEditModal.classList.remove('hidden')}
addRecipeBtn.onclick=()=>openRecipeEditor();addIngredientRowBtn.onclick=()=>addRecipeIngredientRow();closeRecipeEdit.onclick=()=>recipeEditModal.classList.add('hidden');recipeEditModal.onclick=e=>{if(e.target===recipeEditModal)recipeEditModal.classList.add('hidden')};
saveRecipe.onclick=async()=>{const name=recipeEditName.value.trim();const names=[...document.querySelectorAll('.recipe-ing-input')].map(x=>x.value.trim()).filter(Boolean);if(!name){toast('Enter a recipe name');return}try{let rid=editingRecipeId;if(rid){const rr=await api('shop_recipes?id=eq.'+rid,{method:'PATCH',body:JSON.stringify({name})});recipes=recipes.map(x=>x.id===rid?rr[0]:x);await api('shop_recipe_ingredients?recipe_id=eq.'+rid,{method:'DELETE'});recipeIngredients=recipeIngredients.filter(x=>x.recipe_id!==rid)}else{const rr=await api('shop_recipes',{method:'POST',body:JSON.stringify({name,sort_order:recipes.length+1})});rid=rr[0].id;recipes.push(rr[0])}if(names.length){const body=names.map((n,i)=>({recipe_id:rid,ingredient_name:n,sort_order:i+1}));const ir=await api('shop_recipe_ingredients',{method:'POST',body:JSON.stringify(body)});recipeIngredients.push(...ir)}openRecipes.add(rid);recipeEditModal.classList.add('hidden');renderRecipes();toast(editingRecipeId?'Recipe updated':'Recipe added')}catch(e){toast('Could not save recipe')}};
deleteRecipe.onclick=async()=>{if(!editingRecipeId||!confirm('Delete this recipe?'))return;try{await api('shop_recipes?id=eq.'+editingRecipeId,{method:'DELETE'});recipes=recipes.filter(x=>x.id!==editingRecipeId);recipeIngredients=recipeIngredients.filter(x=>x.recipe_id!==editingRecipeId);openRecipes.delete(editingRecipeId);recipeEditModal.classList.add('hidden');renderRecipes();toast('Recipe deleted')}catch(e){toast('Could not delete recipe')}};

async function togglePantry(id){const existing=list.find(l=>l.item_id===id&&!l.purchased);try{if(existing){await api('shop_list?id=eq.'+existing.id,{method:'DELETE'});list=list.filter(x=>x.id!==existing.id)}else{const i=items.find(x=>x.id===id),r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:id,quantity:1,price:i.default_price})});list.push(r[0])}render();}catch(e){toast('Could not update item')}}
async function togglePurchased(id,val){try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({purchased:val,updated_at:new Date().toISOString()})});list=list.map(x=>x.id===id?r[0]:x);render()}catch(e){toast('Could not update item')}}
async function qty(id,d){const x=list.find(l=>l.id===id);if(!x)return;const n=Math.max(1,Number(x.quantity)+d);try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({quantity:n})});list=list.map(y=>y.id===id?r[0]:y);renderShopping()}catch(e){toast('Could not change quantity')}}
async function quickDeletePantry(id){try{await api('shop_items?id=eq.'+id,{method:'DELETE'});items=items.filter(x=>x.id!==id);list=list.filter(x=>x.item_id!==id);render();toast('Pantry item deleted')}catch(e){toast('Could not delete pantry item')}}
async function quickDeleteRecipe(id){if(!confirm('Delete this recipe?'))return;try{await api('shop_recipes?id=eq.'+id,{method:'DELETE'});recipes=recipes.filter(x=>x.id!==id);recipeIngredients=recipeIngredients.filter(x=>x.recipe_id!==id);openRecipes.delete(id);renderRecipes();toast('Recipe deleted')}catch(e){toast('Could not delete recipe')}}
function closePantrySwipes(except=null){document.querySelectorAll('.swipe-item').forEach(el=>{if(el!==except){el.style.transition='transform .18s ease';el.style.transform='translate3d(0,0,0)'}})}
function initPantrySwipes(){initSwipeRows('.swipe-row:not(.recipe-swipe-row)')}function initSwipeRows(selector='.swipe-row'){document.querySelectorAll(selector).forEach(row=>{let startX=0,startY=0,dx=0,tracking=false,horizontal=false;const item=row.querySelector('.swipe-item');item.style.touchAction='pan-y';row.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;closePantrySwipes(item);startX=e.clientX;startY=e.clientY;dx=0;tracking=true;horizontal=false;item.style.transition='none'});row.addEventListener('pointermove',e=>{if(!tracking)return;const x=e.clientX-startX,y=e.clientY-startY;if(!horizontal){if(Math.abs(x)<6&&Math.abs(y)<6)return;if(Math.abs(y)>Math.abs(x)){tracking=false;item.style.transition='transform .18s ease';item.style.transform='translate3d(0,0,0)';return}horizontal=true}dx=Math.min(0,Math.max(-154,x));item.style.transform='translate3d('+dx+'px,0,0)'});const finish=()=>{if(!tracking&&!horizontal)return;item.style.transition='transform .18s ease';item.style.transform=(horizontal&&dx<=-68)?'translate3d(-154px,0,0)':'translate3d(0,0,0)';tracking=false;horizontal=false};row.addEventListener('pointerup',finish);row.addEventListener('pointercancel',finish)})}
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.swipe-row'))closePantrySwipes()});window.addEventListener('scroll',()=>closePantrySwipes(),{passive:true});
function openPantryEdit(id){const i=items.find(x=>x.id===id);if(!i)return;editingPantryId=id;pantryEditName.value=i.name;pantryEditCategory.value=i.category_id;pantryEditPrice.value=i.default_price??'';pantryEditUnit.value=i.unit??'';pantryEditNote.value=i.note??'';pantryEditModal.classList.remove('hidden')}closePantryEdit.onclick=()=>pantryEditModal.classList.add('hidden');pantryEditModal.onclick=e=>{if(e.target===pantryEditModal)pantryEditModal.classList.add('hidden')};savePantryEdit.onclick=async()=>{const i=items.find(x=>x.id===editingPantryId);if(!i)return;const name=pantryEditName.value.trim();if(!name)return;try{const r=await api('shop_items?id=eq.'+editingPantryId,{method:'PATCH',body:JSON.stringify({name,category_id:Number(pantryEditCategory.value),default_price:pantryEditPrice.value===''?null:Number(pantryEditPrice.value),unit:pantryEditUnit.value.trim()||null,updated_at:new Date().toISOString()})});items=items.map(x=>x.id===editingPantryId?r[0]:x).sort((a,b)=>a.name.localeCompare(b.name));pantryEditModal.classList.add('hidden');render();toast('Pantry item updated')}catch(e){toast('Could not update pantry item')}};deletePantryItem.onclick=async()=>{if(!editingPantryId||!confirm('Delete this item from the pantry?'))return;try{await api('shop_items?id=eq.'+editingPantryId,{method:'DELETE'});items=items.filter(x=>x.id!==editingPantryId);list=list.filter(x=>x.item_id!==editingPantryId);pantryEditModal.classList.add('hidden');render();toast('Pantry item deleted')}catch(e){toast('Could not delete pantry item')}};function setFilter(n){filter=n;renderPantry()}search.addEventListener('input',e=>{query=e.target.value;renderPantry()});
document.querySelectorAll('nav button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;shoppingView.classList.toggle('hidden',v!=='shopping');pantryView.classList.toggle('hidden',v!=='pantry');recipesView.classList.toggle('hidden',v!=='recipes');title.textContent=v==='pantry'?'Pantry':v==='recipes'?'Recipes':'Shopping List';addBtn.classList.toggle('hidden',v==='recipes');closePantrySwipes()});
clearPurchased.onclick=async()=>{try{await api('shop_list?purchased=eq.true',{method:'DELETE'});list=list.filter(x=>!x.purchased);render()}catch(e){toast('Could not clear purchased')}};
function openAdd(prefill=''){delete customName.dataset.recipeTarget;customName.value=prefill;customCategory.innerHTML=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');modal.classList.remove('hidden')}addBtn.onclick=()=>openAdd();missingItem.onclick=()=>openAdd(query);closeModal.onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
saveCustom.onclick=async()=>{const name=customName.value.trim(),category_id=Number(customCategory.value);if(!name||!category_id)return;try{let pantry=items.find(i=>i.name.toLowerCase()===name.toLowerCase()&&i.category_id===category_id);if(!pantry){const ir=await api('shop_items',{method:'POST',body:JSON.stringify({name,category_id,default_price:customPrice.value===''?null:Number(customPrice.value)})});pantry=ir[0];items.push(pantry);items.sort((a,b)=>a.name.localeCompare(b.name))}const existing=list.find(l=>l.item_id===pantry.id&&!l.purchased);if(!existing){const r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:pantry.id,quantity:Number(customQty.value)||1,price:customPrice.value===''?pantry.default_price:Number(customPrice.value),note:customNote.value.trim()||null})});list.push(r[0])}customName.value='';customQty.value=1;customPrice.value='';customNote.value='';const recipeTarget=customName.dataset.recipeTarget==='1';delete customName.dataset.recipeTarget;modal.classList.add('hidden');render();if(recipeTarget){const inputs=[...document.querySelectorAll('.recipe-ing-input')];const target=inputs.find(x=>x.value.trim().toLowerCase()===name.toLowerCase());if(target)target.value=pantry.name;toast('Added to Pantry and recipe')}else toast('Saved to pantry and shopping list')}catch(e){toast('Could not add item')}};
function openEdit(id){const x=enriched(list.find(l=>l.id===id));if(!x)return;editingId=id;editItemName.textContent=x.name;editPrice.value=x.price??'';editNote.value=x.note??'';editModal.classList.remove('hidden')}
closeEdit.onclick=()=>editModal.classList.add('hidden');editModal.onclick=e=>{if(e.target===editModal)editModal.classList.add('hidden')};saveEdit.onclick=async()=>{if(!editingId)return;try{const r=await api('shop_list?id=eq.'+editingId,{method:'PATCH',body:JSON.stringify({price:editPrice.value===''?null:Number(editPrice.value),note:editNote.value.trim()||null,updated_at:new Date().toISOString()})});list=list.map(x=>x.id===editingId?r[0]:x);editModal.classList.add('hidden');renderShopping();toast('Item updated')}catch(e){toast('Could not update item')}};
function toast(s){toastEl=document.getElementById('toast');toastEl.textContent=s;toastEl.classList.remove('hidden');setTimeout(()=>toastEl.classList.add('hidden'),1800)}load();