const URL='https://uinhyjqsqrgfczqrmcya.supabase.co';const KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';const H={'apikey':KEY,'Content-Type':'application/json','Prefer':'return=representation'};let categories=[],items=[],list=[],filter='All',query='';
const api=async(path,opt={})=>{const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:{...H,...opt.headers}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()};
const money=n=>n==null?'':('$'+Number(n).toFixed(2));const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){try{[categories,items,list]=await Promise.all([api('shop_categories?select=*&order=sort_order'),api('shop_items?select=*&active=eq.true&order=name'),api('shop_list?select=*&order=added_at')]);render()}catch(e){toast('Could not load data')}}
function enriched(l){const i=items.find(x=>x.id===l.item_id);return{...l,name:i?.name||l.custom_name||'Item',cat:i?.category_id||null,unit:i?.unit||null,price:l.price??i?.default_price??null}}
function render(){renderShopping();renderPantry()}
function renderShopping(){const active=list.filter(x=>!x.purchased).map(enriched),done=list.filter(x=>x.purchased).map(enriched);itemCount.textContent=active.length+' item'+(active.length===1?'':'s');total.textContent=money(active.reduce((s,x)=>s+(Number(x.price)||0)*Number(x.quantity),0));shoppingGroups.innerHTML='';
 const grouped=new Map();active.forEach(x=>{const k=x.cat||0;if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(x)});
 [...grouped.entries()].sort((a,b)=>(categories.find(x=>x.id===a[0])?.sort_order||99)-(categories.find(x=>x.id===b[0])?.sort_order||99)).forEach(([cid,arr])=>shoppingGroups.insertAdjacentHTML('beforeend',groupHTML(categories.find(c=>c.id===cid)?.name||'Other',arr,false)));
 if(!active.length)shoppingGroups.innerHTML='<div class="empty">Your shopping list is clear.<br>Add items from Pantry.</div>';
 completedWrap.classList.toggle('hidden',!done.length);completedCount.textContent=done.length;completedList.innerHTML=done.length?'<div class="card purchased">'+done.map(x=>itemHTML(x,true)).join('')+'</div>':''}
function groupHTML(name,arr,done){return '<div class="group"><div class="group-title">'+esc(name)+'</div><div class="card">'+arr.map(x=>itemHTML(x,done)).join('')+'</div></div>'}
function itemHTML(x,done){return '<div class="item"><button class="check '+(done?'on':'')+'" onclick="togglePurchased('+x.id+','+!done+')">'+(done?'✓':'')+'</button><div class="item-info"><div class="item-name">'+esc(x.name)+'</div><div class="item-meta">'+(x.unit?esc(x.unit):'')+'</div></div>'+(!done?'<div class="qty"><button onclick="qty('+x.id+',-1)">−</button><span>'+Number(x.quantity)+'</span><button onclick="qty('+x.id+',1)">+</button></div>':'')+'<div class="price">'+money(x.price)+'</div></div>'}
function renderPantry(){chips.innerHTML=['All',...categories.map(c=>c.name)].map(n=>'<button class="chip '+(filter===n?'active':'')+'" onclick="setFilter(\''+n.replaceAll("'","\\'")+'\')">'+esc(n)+'</button>').join('');
 const cat=categories.find(c=>c.name===filter);const q=query.toLowerCase();const shown=items.filter(i=>(filter==='All'||i.category_id===cat?.id)&&i.name.toLowerCase().includes(q));const groups=filter==='All'?categories:categories.filter(c=>c.id===cat?.id);pantryList.innerHTML='';
 groups.forEach(c=>{const a=shown.filter(i=>i.category_id===c.id);if(a.length)pantryList.insertAdjacentHTML('beforeend','<div class="group"><div class="group-title">'+esc(c.name)+'</div><div class="card">'+a.map(i=>{const on=list.some(l=>l.item_id===i.id&&!l.purchased);return '<div class="item"><div class="item-info"><div class="item-name">'+esc(i.name)+'</div><div class="item-meta">'+[money(i.default_price),i.unit].filter(Boolean).join(' · ')+'</div></div><button class="pantry-add '+(on?'added':'')+'" onclick="togglePantry('+i.id+')">'+(on?'✓ Added':'+ Add')+'</button></div>'}).join('')+'</div></div>')});if(!pantryList.innerHTML)pantryList.innerHTML='<div class="empty">No pantry items found.</div>'}
async function togglePantry(id){const existing=list.find(l=>l.item_id===id&&!l.purchased);try{if(existing){await api('shop_list?id=eq.'+existing.id,{method:'DELETE'});list=list.filter(x=>x.id!==existing.id)}else{const i=items.find(x=>x.id===id),r=await api('shop_list',{method:'POST',body:JSON.stringify({item_id:id,quantity:1,price:i.default_price})});list.push(r[0])}render();}catch(e){toast('Could not update item')}}
async function togglePurchased(id,val){try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({purchased:val,updated_at:new Date().toISOString()})});list=list.map(x=>x.id===id?r[0]:x);render()}catch(e){toast('Could not update item')}}
async function qty(id,d){const x=list.find(l=>l.id===id);if(!x)return;const n=Math.max(1,Number(x.quantity)+d);try{const r=await api('shop_list?id=eq.'+id,{method:'PATCH',body:JSON.stringify({quantity:n})});list=list.map(y=>y.id===id?r[0]:y);renderShopping()}catch(e){toast('Could not change quantity')}}
function setFilter(n){filter=n;renderPantry()}search.addEventListener('input',e=>{query=e.target.value;renderPantry()});
document.querySelectorAll('nav button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.dataset.view==='pantry';shoppingView.classList.toggle('hidden',p);pantryView.classList.toggle('hidden',!p);title.textContent=p?'Pantry':'Shopping';addBtn.classList.toggle('hidden',p)});
document.getElementById('clearPurchased').onclick=async()=>{try{await api('shop_list?purchased=eq.true',{method:'DELETE'});list=list.filter(x=>!x.purchased);render()}catch(e){toast('Could not clear purchased')}};
addBtn.onclick=()=>modal.classList.remove('hidden');closeModal.onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
saveCustom.onclick=async()=>{const name=customName.value.trim();if(!name)return;try{const r=await api('shop_list',{method:'POST',body:JSON.stringify({custom_name:name,quantity:Number(customQty.value)||1,price:customPrice.value===''?null:Number(customPrice.value)})});list.push(r[0]);customName.value='';customQty.value=1;customPrice.value='';modal.classList.add('hidden');render();toast('Added to shopping list')}catch(e){toast('Could not add item')}};
function toast(s){toastEl=document.getElementById('toast');toastEl.textContent=s;toastEl.classList.remove('hidden');setTimeout(()=>toastEl.classList.add('hidden'),1800)}load();